config/routes.rb
Rails.application.routes.draw do
	resources :pins do
		member do
			put "like", to: "pins#upvote"
		end
	end
		

  devise_for :users
	root 'pins#index'
	get "about" => "pages#about" #creates the about_path
  

	 

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	acts_as_votable
	belongs_to :user
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"	
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
	validates :image, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	validates :name, presence: true
	has_many :pins, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
	before_filter :configure_permitted_parameters, if: :devise_controller?

protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :name
   devise_parameter_sanitizer.for(:account_update) << :name
 end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
	
	def about
	end	
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
	before_action :set_pin, only: [:show, :edit, :update, :destroy ,:upvote]
	before_action :authenticate_user!, except: [:index, :show]
	before_action :correct_user, only: [:edit, :update, :destroy]
 
	respond_to :html

  def index
		@pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page =>6)
    respond_with(@pins)
  end

  def show
    respond_with(@pin)
  end

  def new
		@pin = current_user.pins.build
    respond_with(@pin)
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
			flash[:info] ='Pin was successfully created.'
			respond_with(@pin)			
    else
      render action: 'new'
    end
  end

  def update
   if @pin.update(pin_params)
		 flash[:info] = 'Pin was successfully updated.'
		 redirect_to @pin
	 else
		 render action: 'edit'
	 end
  end

  def destroy
    @pin.destroy
    respond_with(@pin)
  end

	def upvote
		@pin.upvote_by current_user
		redirect_to :back		
	end
	
  private
    def set_pin
			@pin = Pin.find_by(id: params[:id])
    end
		
		def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end

    def pin_params
			params.require(:pin).permit(:description,:image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
 <div class="container">
 		<!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
		<%= link_to "Pinbox", root_path, class:"navbar-brand" %>    
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li>
			<% if user_signed_in? %>				
          <li>
            <%= link_to new_pin_path do %>
              <span class="glyphicon glyphicon-plus"></span> New Pin
            <% end %>
          </li>
				<li><%= link_to "Account Settings", edit_user_registration_path %></li>
				<li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
			<% else %>
			<li><%= link_to "Sign in", new_user_session_path %></li>
			<% end %>
    </ul>
  </div><!-- /.navbar-collapse --> 		
 </div><!-- /.container  -->
</nav>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : (name == 'info' ? 'info' : 'danger' )%>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinbox</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

	<%= render 'layouts/header' %>
	<div class="container">
		<%= render 'layouts/messages' %>	
		<%= yield %>	
	</div>	

</body>
</html>

app/views/pages/_home.html.erb
<div class="jumbotron center">		
	<h1>Welcome to <strong class="app_brand">Pinbox</strong></h1>
	<p>Never forget your interests again!</p>
	<div>
		<%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
		<%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
	</div>	  
</div>

app/views/pages/about.html.erb
<h1>About us</h1>
<p>Getting started to work on making the pininterest clone!</p>

app/views/pages/home.html.erb
<div class="jumbotron center">		
	<h1>Welcome to my app!</h1>
	<% if user_signed_in? %>
		#do something
	<% else %>
		<div>
		<%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
		<%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
	</div>
	<% end %>
	  
</div>

app/views/pins/_form.html.erb
<%= form_for@pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
	<div class="form-group">
		<%= f.label :image %><br>
		<%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  
  <div class="form-group">
		<%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>

<div id="pins" class="transitions-enabled">
	<% @pins.each do |pin| %>	
		<div class="box panel panel-default">			
			<%= link_to image_tag(pin.image.url(:medium)), pin %>
			<div class="panel-body">	
				<h4><%= link_to pin.description, pin %></h4>
				<p class="user_name"><strong><%= pin.user.name if pin.user %></strong></p>				
			</div>
		</div>		
	<% end %>
</div>
<div class="center">
	<%= will_paginate @pins, renderer: BootstrapPagination::Rails %>
</div>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<%= link_to 'Back', pins_path %>

<div class="row" id="pin_show">
  <div class="col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading pin_image">
        <%= image_tag @pin.image.url(:medium) %>
      </div>
      <div class="panel-body">
        <p class="description"><%= @pin.description %></p>
			</div>
      <div class="panel-footer">
      	<div class="row">
      		<div class="col-md-6">
						<p class="user_show"><%= @pin.user.name if @pin.user %></p>
					</div>
					<div class="col-md-6">
						<div class="btn-group pull-right">
							<%= link_to like_pin_path(@pin), method: :put, class: "btn btn-default show-buttons" do %>
							<span class="glyphicon glyphicon-heart"></span> <%= @pin.get_upvotes.size %>
							<% end %>
							<% if current_user && @pin.user == current_user %>
								<%= link_to edit_pin_path(@pin), class: "btn btn-default show-buttons" do %>
									<span class="glyphicon glyphicon-edit"></span> Edit
								<% end %>
								<%= link_to pin_path, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-default show-buttons " do %>
									<span class="glyphicon glyphicon-trash"></span> Delete
								<% end %>
							<% end %>
						</div>
					</div>
				</div>
      </div>
    </div>
  </div>
</div>